### ISSUE TITLE
Add issue template and PR template

### ISSUE THREAD

**Issue by enpuyou** [inTestiGator/pytest-santa#10]

**Comment by korzeniwskya** [comment]
Added Issue Templates, April 2nd 3:14pm. Three basic templates added, bugs, features, custom.

**Comment by korzeniwskya** [comment]
Adding Documentation for PR Templates.

**Comment by korzeniwskya** [comment]
Updated Pull Request, Pending review.

**Comment by korzeniwskya** [comment]
Once the pull request has been merged this issue can be closed!

**Comment by Michionlion** [comment]
@korzeniwskya if you mention this issue like `fixes #10` in the PR description, when the PR is merged this issue will automatically be closed.
